targets:
  $default:
    sources:
      - $package$
      - lib/**
      - .env
      - pubspec.yaml
    builders:
      flutter_gen_runner:
        options:
          output: lib/gen/
      json_serializable:
        options:
          field_rename: none 
        generate_for:
          - lib/app/modules/**/*.dart
      retrofit_generator:
        generate_for:
          - lib/app/modules/**/*.dart