targets:
  $default:
    sources:
      - lib/**
      - .env
      - $package$
    builders:
      json_serializable:
        options:
          field_rename: none 
        generate_for:
          - lib/app/modules/**/data/**/*.dart
      retrofit_generator:
        generate_for:
          - lib/app/modules/**/data/**/*.dart