name: Build Android APK

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.32.8"

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter Version Manager (FVM)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install FVM
        run: |
          dart pub global activate fvm
          fvm install ${{ env.FLUTTER_VERSION }}
          fvm use ${{ env.FLUTTER_VERSION }} --force

      - name: Flutter version
        run: fvm flutter --version

      - name: Get Flutter dependencies
        run: fvm flutter pub get

      - name: Create .env file
        run: |
          echo "API_URL=${{ secrets.API_BASE_URL }}" > .env
          echo "PUBLIC_STORAGE=${{ secrets.PUBLIC_STORAGE }}" >> .env

      - name: Generate code with build_runner
        run: fvm dart run build_runner build --delete-conflicting-outputs

      - name: Generate localizations
        run: fvm flutter gen-l10n

      - name: Create google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - name: Create firebase_options.dart
        env:
          firebase_options_dart: ${{secrets.FIREBASE_OPTIONS_DART}}
        run : echo "$firebase_options_dart" > lib/firebase_options.dart

      - name: Setup Android signing
        uses: android-actions/setup-android@v3

      - name: Build APK with obfuscation
        run: |
          fvm flutter build apk \
            --release \
            --obfuscate \
            --split-debug-info=build/debug-info \
            --dart-define=FLUTTER_BUILD_MODE=release \
            --target=lib/main.dart

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
          groups: pre-testers
          releaseNotesFile: release-notes.txt || release-notes.md
          file: build/app/outputs/flutter-apk/app-release.apk